version: '3.8'
services:
  postgres:
    image: 'postgres:16.2'
    container_name: 'book-manager-postgres'
    environment:
      POSTGRES_DB: mybook
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: